name: Run Semgrep
on:
  pull_request:
    branches:
      - '*'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --gitlab-sast --output semgrep.json\
            --metrics=off \
            --config="p/default"

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep_report
          path: semgrep.json

      - name: Create edited report
        run: |
          cat semgrep.json | jq '[.vulnerabilities[] | { category, description, location, severity }]' > semgrep_edited.json
        
      - name: Save edited report
        uses: actions/upload-artifact@v4
        with:
          name: edited_report
          path: semgrep_edited.json

      - name: Display in the console
        run: |
          cat semgrep_edited.json
      
      - name: Find and Update Comment with Semgrep Results
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const semgrepResults = fs.readFileSync('semgrep_edited.json', 'utf8');
            const pr_number = context.payload.pull_request.number;

            const comments = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
            });

            const existingComment = comments.data.find(comment => comment.body.includes('Semgrep analysis results:'));

            if (existingComment) {
              await github.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: `Semgrep analysis results:\n\`\`\`json\n${semgrepResults}\n\`\`\``,
              });
            } else {
              await github.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Semgrep analysis results:\n\`\`\`json\n${semgrepResults}\n\`\`\``,
              });
            }   