name: Trivy Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '1.11'

      - name: Install Erlang
        run: |
          sudo apt-get update
          sudo apt-get install -y erlang

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.39.1/trivy_0.39.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.39.1_Linux-64bit.deb

      - name: Run Trivy scan
        run: |
          # Сканирование проекта Java
          trivy fs --format sarif --output trivy-report-java.sarif .

          # Сканирование проекта Erlang
          # Предположим, что ваш проект использует rebar3 для управления зависимостями
          rebar3 compile
          trivy fs --format sarif --output trivy-report-erlang.sarif .

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: |
            trivy-report-java.sarif
            trivy-report-erlang.sarif